git:
  depth: 1
branches:
  except: /^v\d/
language: node_js
node_js: node
before_install:
  - rvm use 2.3.3 --install --binary --fuzzy
  - gem install cocoapods
  - pod --version
  - pod setup
script: npm run-script pretest && npm run-script coverage
after_script:
  - npm install istanbul-coveralls
  - node node_modules/.bin/istanbul-coveralls
