git:
  depth: 1
branches:
  except: /^v\d/
language: node_js
node_js: stable
before_install:
  - rvm install 2.2.2
  - rvm use 2.2.2
  - gem install cocoapods
  - pod --version
  - pod setup
script:
  - npm run-script pretest
  - npm run-script coverage
after_script:
  - npm install istanbul-coveralls
  - node node_modules/.bin/istanbul-coveralls
notifications:
  email: false
